apiVersion: v1

kind: Pod
metadata:
  name: bbox-pod
  namespace: student

spec:
  nodeSelector:
    mem: high

  containers:
    - image: busybox
      name: bbox-cont
      command: 
        - bin/sh
        - -c
        - ping 1.1.1.1

