kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-all-bind
    namespace: training

subjects:
        - kind: ServiceAccount
          name: student
          namespace: training

roleRef:
          kind: ClusterRole
          name: readers-limited1
          apiGroup: 'rbac.authorization.k8s.io'         

