kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-limited1
    namespace: training 
    #  labels:

rules:
  - apiGroups: [""]
    resources: ["namespaces","pods","pods/log","nodes","services"]
    verbs: ["get","list","watch"] 
  
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch"] 

  - apiGroups: ["batch"]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    resources: ["*"]
    verbs: ["get","list","watch"]
